### PR TITLE
Always rotate images to ensure correct orientation

### PR DESCRIPTION
**Pull request by nosecreek**
#132 solved the issue of some images not being rotated properly due to not respecting EXIF data. However, some images are still not being rotated correctly, especially landscape images that may have been shot upside down (rotated 180 degrees). For example, on an iPhone it is easy to shoot landscape images with either edge of the phone "up" - half of these photos will end up rotated incorrectly. This pull request fixes the issue by always calling .rotate() to ensure images have the correct orientation.

### CODE REVIEW

**Comment by furius95** [comment]
I’m still encountering this problem quite often, in exactly the circumstances nosecreek describes above

**Comment by GHF** [comment]
I agree with this approach of always calling sharp `rotate`, because EXIF orientations 2–4 also require processing, even though the result would have the same dimensions as the original. The [documentation of `rotate`](https://sharp.pixelplumbing.com/api-operation#rotate) says

> If no angle is provided, it is determined from the EXIF data. **Mirroring is supported and may infer the use of a flip operation.**

I'm not sure how to test for this with a dry run, however.

**Comment by zachleat** [comment]
I’ll merge this one for v3.1.9 but as an opt-in feature. I don’t think I want to apply this by default to every image before we prove that the performance cost is negligible.

**Comment by zachleat** [comment]
Use the `fixOrientation: true` option to opt-in to this feature!

**Comment by zachleat** [comment]
Changed to v3.2.0

**Pull request merged**
