### PR TITLE
Maintant orientation specified in EXIF data

### PR DESCRIPTION
**Pull request by stlk**
Based on discussion and work done in #93 I modified the code to rotate image and update dimensions.

### CODE REVIEW

**Comment by btrem** [comment]
Does this pr resolve issues in #93? If not, what work needs to be done?

**Comment by stlk** [comment]
> Does this pr resolve issues in #93? If not, what work needs to be done?

Yes, it does.

**Comment by zachleat** [comment]
I’m using and linking up some invaluable test cases for this here https://github.com/recurser/exif-orientation-examples

**Comment by zachleat** [comment]
Thank you!

**Pull request merged**
